### ISSUE TITLE
Kentucky Server is down.

### ISSUE THREAD

**Issue by krichards4** [ngds/service-notifications#17]
I have emailed Doug about it.

**Comment by dougcurl** [comment]
Update about this: we are having a lot of issues with our current GIS / web server - the KGS servers are basically at capacity with memory/processing due to the number of services running and increasing number of hits. But, we have a new server we are about to deploy - hopefully early next week. The new GIS server will be robust and virtualized with server 2012 (so we can finally participate with the failover scenarios) and will be separate from our web server.  Until then, you can expect up and down issues with the existing services. Will update you all when we get that online. Thanks for the patience and I apologize for the inconvenience.

**Comment by dougcurl** [comment]
Update - the KGS server is switched over to our new 10.21 server. It seems to be running well, but let me know, of course, if you have any issues. The only thing about it is that it seems on the first load of a service, it's relatively slow (a few seconds to view the REST page), but seems to improve on subsequent hits.
